language: python

python:
  - "3.8"
  - "3.7"

install: pip install tox-travis

script: tox

deploy:
  provider: pypi
  username: jacobneiltaylor
  distributions: "sdist bdist_wheel"
  skip_existing: true
  edge: true